-- Run this in the Supabase SQL Editor.

create table public.observations (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  group_name text not null,
  observation_type text not null check (
    observation_type in ('Trail width', 'Wet trail', 'Other')
  ),
  note text,
  measurement text,
  latitude double precision not null,
  longitude double precision not null,
  gps_accuracy double precision not null,
  photo_url text
);

alter table public.observations enable row level security;

create policy "Anyone can read observations"
on public.observations
for select
to anon
using (true);

create policy "Anyone can add observations"
on public.observations
for insert
to anon
with check (true);

create policy "Anyone can update observations"
on public.observations
for update
to anon
using (true)
with check (true);

-- Photo storage bucket.
insert into storage.buckets (id, name, public)
values ('observation-photos', 'observation-photos', true)
on conflict (id) do update set public = true;

-- Allow anonymous users to upload photos.
create policy "Anyone can upload observation photos"
on storage.objects
for insert
to anon
with check (bucket_id = 'observation-photos');

-- Allow anonymous users to view photos.
create policy "Anyone can view observation photos"
on storage.objects
for select
to anon
using (bucket_id = 'observation-photos');
